### PR TITLE
Bump tree-sitter version to 0.20

### PR DESCRIPTION
**Pull request by VixieTSQ**

### CODE REVIEW

**Comment by alexlafroscia** [comment]
Thanks for this PR! I haven't been keeping up with the `tree-sitter` world much these days; can you help me understand the potential impact of this update?

For example, I wrote this grammar for NeoVim originally; do you know if they support this version of `tree-sitter`?

Does this constitute a breaking change for the grammar?

Should the [`tree-sitter-cli`](https://github.com/alexlafroscia/tree-sitter-glimmer/blob/490a7f1d284a978e9b4b1a460f5ccd8c0db19a56/package.json#L19) package also be updated?

**Comment by alexlafroscia** [comment]
Also, it seems like the listing check no longer passes; if you could fix that, I'd really appreciate it!

**Review by alexlafroscia — COMMENTED** [review]
Did the changes in 23b9c87d55d010323340f855a2ce900723b947ea come from a generator that you ran to update the files? Or were those edits manually made?

**Comment by VixieTSQ** [comment]
> Did the changes in [23b9c87](https://github.com/alexlafroscia/tree-sitter-glimmer/commit/23b9c87d55d010323340f855a2ce900723b947ea) come from a generator that you ran to update the files? Or were those edits manually made?

Some of the changes were from the generator. The changes I made to the rust binding and .gitignore were manual

**Comment by VixieTSQ** [comment]
> For example, I wrote this grammar for NeoVim originally; do you know if they support this version of `tree-sitter`?
> 
> Does this constitute a breaking change for the grammar?

I'm not entirely sure actually. I made this pull to help with the rust binding. I don't know anything about neovim but I believe it should still work. The changes made to the actual parser.c file by the generator are very minimal and I think I've seen the rust binding work without those changes. The rest of the changes are really rust specific

**Comment by alexlafroscia** [comment]
Thanks for the PR!

**Comment by alexlafroscia** [comment]
This was just released to `npm` as version `1.2.0`. Thanks again!

**Pull request merged**
